name: test-kubepug

on:
  push:
  pull_request:

jobs:
  test_kubepug_action:
    runs-on: ubuntu-latest
    permissions: {}
    name: Install kubepug and test presence in path
    steps:
    - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
    - name: Install kubepug
      uses: ./
    - name: Check install!
      run: kubepug --version
    - name: Check root directory
      run: |
        if [[ $(git diff --stat) != '' ]]; then
          echo 'should be clean'
          exit 1
        else
          exit 0
        fi

  test_kubepug_action_wrong:
    runs-on: ubuntu-latest
    permissions: {}
    name: Try to install a wrong kubepug
    steps:
    - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
    - name: Install kubepug
      uses: ./
      with:
        kubepug-release: 'honk'
      continue-on-error: true
